<?php

/**
 * Filter QR Security Events API
 * Returns security events generated by strict QR/Face binding flow.
 */

require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/../includes/qr_binding_helper.php';

header('Content-Type: application/json');
send_api_security_headers();
require_same_origin_api_request();

if ($_SERVER['REQUEST_METHOD'] !== 'GET') {
    http_response_code(405);
    echo json_encode(['success' => false, 'error' => 'Method not allowed']);
    exit;
}

if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
    http_response_code(401);
    echo json_encode(['success' => false, 'error' => 'Unauthorized']);
    exit;
}

require_permission('audit.read', [
    'actor_role' => 'admin',
    'response' => 'json',
    'message' => 'Forbidden: missing permission audit.read.',
]);

$headers = getallheaders();
$csrfHeader = $headers['X-CSRF-Token'] ?? $headers['x-csrf-token'] ?? '';
if (empty($csrfHeader) || !hash_equals($_SESSION['csrf_token'] ?? '', $csrfHeader)) {
    http_response_code(403);
    echo json_encode(['success' => false, 'error' => 'Invalid security token']);
    exit;
}

try {
    $pdo = pdo();
    ensure_qr_binding_tables($pdo);
    qr_binding_expire_stale_rows($pdo);

    $query = "SELECT * FROM qr_security_events WHERE 1=1";
    $params = [];

    if (!empty($_GET['event_type'])) {
        $query .= " AND event_type = ?";
        $params[] = (string)$_GET['event_type'];
    }

    if (!empty($_GET['date_from'])) {
        $query .= " AND DATE(created_at) >= ?";
        $params[] = (string)$_GET['date_from'];
    }

    if (!empty($_GET['date_to'])) {
        $query .= " AND DATE(created_at) <= ?";
        $params[] = (string)$_GET['date_to'];
    }

    if (!empty($_GET['user_id'])) {
        $query .= " AND user_id = ?";
        $params[] = (int)$_GET['user_id'];
    }

    if (!empty($_GET['student_id'])) {
        $query .= " AND student_id = ?";
        $params[] = (string)$_GET['student_id'];
    }

    $query .= " ORDER BY created_at DESC LIMIT 200";

    $stmt = $pdo->prepare($query);
    $stmt->execute($params);
    $rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

    echo json_encode([
        'success' => true,
        'events' => $rows,
        'count' => count($rows)
    ]);
} catch (Throwable $e) {
    error_log('QR security event filter error: ' . $e->getMessage());
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'error' => 'Failed to load QR security events'
    ]);
}
